### ISSUE TITLE
Error caused by updating to 2.3.0

### ISSUE THREAD

**Issue by Kleppo** [canjs/can-define#336]
When I update from 2.0.3 to 2.3.0 I get this error when running my app:

`
steal.js:7977 TypeError: obj.hasOwnProperty is not a function

	    at Object.size (shape.js:1034)
	    at DefineMap.define.setup (can-define.js:985)
	    at DefineMap.setup (map.js:126)
	    at Function.newInstance (can-construct.js:289)
	    at DefineMap.init (can-construct.js:637)
	    at new DefineMap (eval at <anonymous> (can-construct.js:NaN), <anonymous>:3:32)
	    at DefineList.observable [as __type] (can-define.js:1072)
	    at DefineList.splice (list.js:527)
	    at DefineList.setup (list.js:117)
	    at Function.newInstance (can-construct.js:289)

logErrors @ steal.js:7977
tryCatchReject @ steal.js:1183
runContinuation1 @ steal.js:1142
Rejected.when @ steal.js:963
Pending.run @ steal.js:821
Scheduler._drain @ steal.js:97
Scheduler.drain @ steal.js:62
run @ steal.js:268
`

**Comment by justinbmeyer** [comment]
Thanks for reporting. I will fix this in about 3 hrs.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-reflect #109](https://github.com/canjs/can-reflect/issues/109) via [**ZenHub**](https://www.zenhub.com/)

**Comment by justinbmeyer** [comment]
@Kleppo I'm having trouble re-creating this.   I thought it was a problem with `can-reflect`, but I'm unable to cause what I thought the problem was.

Does like 985 look like this:

```
	if(canReflect.size(instanceDefinitions) > 0) {
		defineConfigurableAndNotEnumerable(this, "_instanceDefinitions", instanceDefinitions);
	}
```

What does `instanceDefinitions` look like for you?

**Comment by justinbmeyer** [comment]
Ah, it looks like you're using an old version of `can-reflect`.  I'll update can-define to require the new version.

**Comment by justinbmeyer** [comment]
I think it needs at least `can-reflect@^1.15.0`
